### ISSUE TITLE
App doesn't work when run locally

### ISSUE THREAD

**Issue by ZooeyMiller** [FACG2/Pied-Piper-Autocomplete#10]
Because you've [hardcoded the link to heroku in your frontend code](https://github.com/FACG2/Pied-Piper-Autocomplete/blob/master/public/js/index.js#L7-L10) the app does not work when run locally because of CORS. 

If instead of putting the whole url in the front end code if you did `'./your-endpoint-here'` then the link would always go to your given endpoint added to the domain you're currently on, meaning this would work wherever the server was being run.

**Comment by Eslam3bed** [comment]
YA ,we missed it 
we should adjust it to be like this:
```javascript
var urls={
	coun:'./api/country/?q=',
	uni:'./api/uni/?q=',
	sUn:'./api/getUni/?q=',
	reqNum:'./api/getReqStatus'
}
```

**Comment by mahmoudalwadia** [comment]
fixed !

**Comment by ZooeyMiller** [comment]
Looks good! Remember when you commit or make a pull request you can link the issue in the body of the PR or the commit message so I could see where you fixed it as well :wink:
