### ISSUE TITLE
Not found handler not being used in router

### ISSUE THREAD

**Issue by ZooeyMiller** [FACG2/Pied-Piper-Autocomplete#14]
Currently, in your router your default statement (the `else` block of the if/else chain) you use `homeHandler` which just server the home route, which means I can do things like this:

![peek 2017-08-03 09-25](https://user-images.githubusercontent.com/21139983/28908738-df564ca8-782d-11e7-8f89-b7b7ac7224bb.gif)

If I mash random keys as an endpoint, I should definitely be getting a `404`, not the homepage!

**Comment by Eslam3bed** [comment]
Fixed :+1: 
![screenshot from 2017-08-03 11-10-22](https://user-images.githubusercontent.com/20760072/28912339-850091a0-783c-11e7-941e-df8cdcaffc4d.png)

**Comment by ZooeyMiller** [comment]
Was very happy to see this in your presentation!
