### ISSUE TITLE
responsive issu

### ISSUE THREAD

**Issue by Walidmash** [FACG2/Pied-Piper-Autocomplete#15]
![screenshot from 2017-08-03 09-26-48](https://user-images.githubusercontent.com/20396442/28908812-3c8c2640-782e-11e7-9efe-62e95f573997.png)

**Comment by Sohadwd** [comment]
![iss](https://user-images.githubusercontent.com/28750873/28908910-d1a1db76-782e-11e7-8126-db7856f53c3e.png)

**Comment by mahmoudalwadia** [comment]
there no responsive issues you have to check your browsers guys!

**Comment by Walidmash** [comment]
@mahmoudalwadia i tested it on 3 laptop and same problem ! 
it can be fixed using media query , and put this code in mobile version 
```
.form-panel input{
width:100%
}
```
